### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by NeoMatrixJR** [govindsartaj/grinnellvaccine#1]
I'm hoping this is for grinnellvaccine.tech site.  I signed up using US Cellular's email -> SMS gateway <number>@email.uscc.net, but it's cutting off most of the email portion.  I can't access the link to cancel getting the emails!  Thank you so much for this...I was able to use this and a few other tools to get an appointment!

**Comment by govindsartaj** [comment]
@NeoMatrixJR We have unsubscribed your email manually. Great to hear that you got an appointment! Stay safe!

**Comment by govindsartaj** [comment]
Closing issue (resolved)!
